version: '2'

services:
    web:
        image: nginx:alpine
        ports:
            - "8888:80"
        volumes:
            - ./src:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        links:
           - app1
    app1:
        image: php:7.1-fpm
        volumes:
            - ./src:/var/www/html
            - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
            - ./docker/php/pool.conf:/usr/local/etc/php-fpm.d/pool.conf
        expose:
            - "9000"
    app2:
        image: php:7.1-fpm
        volumes:
            - ./src:/var/www/html
            - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
            - ./docker/php/pool.conf:/usr/local/etc/php-fpm.d/pool.conf
        expose:
            - "9000"